#!/Users/ecardenas/.rbenv/shims/ruby

require "optparse"

parser = OptionParser.new

parser.on('--xxx', "Long name") do |value|
  p ["-xxx", value]
end

parser.on("--y1%", "--z2#", "Two long names") do |value|
  p ["--y1% pr --z2#", value]
end

parser.require_exact = true
parser.parse!